### ISSUE TITLE
Doesn't work on latest patch

### ISSUE THREAD

**Issue by ElPumpo** [grasmanek94/SkipIntro#1]

**Comment by grasmanek94** [comment]
Please do exactly specify the version/build number and the type of the game (steam or retail).

**Comment by ElPumpo** [comment]
v1.68 retail

**Comment by grasmanek94** [comment]
Are you sure there is a version 1.68? The newest build on steam is 1032 and Online Version is 1.39 (v1.0.1032.1).

I updated today and SkipIntro still works. Paste your asiloader.log and ScriptHookV.log here.

**Comment by ElPumpo** [comment]
v1.36 - build 877
Just doesn't work.

> An update for this would be great! Doesn't work on newer version of the game. 

-William_Evans on http://gta5-mods.com

> // GTA V ASI LOADER (build May  2 2015)
//     (C) Alexander Blade 2015
LIB: "C:\WINDOWS\system32\dinput8.dll" => 00007FFC562F0000
API: "DirectInput8Create" => 00007FFC562F9C00
API: "DllCanUnloadNow" => 00007FFC56309770
API: "DllGetClassObject" => 00007FFC56309840
API: "DllRegisterServer" => 00007FFC56313190
API: "DllUnregisterServer" => 00007FFC56313400
LOADER: Loading *.asi plugins
ASI: Loading "D:\Spel\Grand Theft Auto V\OpenIV.asi"
     "OpenIV.asi" => 00007FFC64850000
ASI: Loading "D:\Spel\Grand Theft Auto V\SkipIntro.asi"
     "SkipIntro.asi" => 00007FFC573E0000
LOADER: Finished loading *.asi plugins

**Comment by grasmanek94** [comment]
I think this is a user error. I would try only loading the SkipIntro.asi with ScriptHookV (not any other loader, no ragehook, no openiv, no other stuff). It will work then. 

The .asi *must* be loaded before the intro. As far as I know OpenIV (and RageHook?) don't load ASI's before the intro. Users should report the bug there.
