### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by Michael21107** [grasmanek94/SkipIntro#2]
the readme says ''Requires a compatible V .ASI loader (Tested only on ScriptHookV)''
but SHV isn't a .asi loader, dinput8 is the only thing I know of that is one, with SHV being an additional .dll file to make some .asi files work
I think you should reword the readme to avoid any confusion

**Comment by grasmanek94** [comment]
Good spot, I've changed the readme.

If there's anything else let me know, and if you consider the clarification okay please close the ticket.

**Comment by Michael21107** [comment]
all i needed to know, thanks a lot
